import { useState } from "react";
import { AlertTriangle, CheckCircle2, FileCheck2, Loader2, LockKeyhole, Plus } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useTranslation } from "@/lib/i18n";
import type { BriefReadinessView, BriefStreamView, BriefVersionView } from "./types";

export type BriefWorkflowAction = "revise" | "evidence" | "finding" | "resolve_finding" | "condition" | "resolve_condition" | "propose_na" | "review_na" | "approve_na" | "review" | "approve";
type Action = (action: BriefWorkflowAction, sectionId: string, detail: string, targetId?: string, dependencyIds?: string[], ownerUserId?: number) => void;
type Props = { streams: BriefStreamView[]; selectedStreamId?: number|string; version?: BriefVersionView; readiness?: BriefReadinessView; issues?: any[]; isLoading?: boolean; error?: string; isCreating?: boolean; isIssuing?: boolean; canAttemptIssue?: boolean; onSelectStream:(id:number|string)=>void; onCreateStream:()=>void; onCreateVersion?:()=>void; onIssue:()=>void; onRetry:()=>void; onSectionAction?:Action; onAssignRole?:(userId:number,role:string)=>void; onRevokeRole?:(id:string)=>void };
const label = (value?: string) => value ? value.replace(/_/g," ").replace(/\b\w/g,c=>c.toUpperCase()) : "Missing";

export function BriefWorkspace(props: Props) {
  const { t, dir } = useTranslation();
  const [open,setOpen]=useState<string>(); const [detail,setDetail]=useState(""); const [target,setTarget]=useState(""); const [deps,setDeps]=useState(""); const [owner,setOwner]=useState("");
  const [roleUser,setRoleUser]=useState(""); const [role,setRole]=useState("author"); const [grant,setGrant]=useState("");
  if(props.isLoading) return <Card aria-busy="true"><CardContent className="flex min-h-48 items-center justify-center gap-2"><Loader2 className="h-5 w-5 animate-spin"/>Loading governed brief…</CardContent></Card>;
  if(props.error) return <Card role="alert"><CardContent className="flex min-h-48 flex-col items-center justify-center gap-3"><AlertTriangle/><p>{props.error}</p><Button onClick={props.onRetry}>Try again</Button></CardContent></Card>;
  if(!props.streams.length) return <Card><CardContent className="flex min-h-56 flex-col items-center justify-center gap-3 text-center"><FileCheck2/><h2>No governed brief yet</h2><Button onClick={props.onCreateStream} disabled={props.isCreating}><Plus className="me-2 h-4 w-4"/>Create governed brief</Button></CardContent></Card>;
  const sections=props.readiness?.sections ?? props.version?.sections ?? []; const reasons=props.readiness?.reasons ?? props.readiness?.deficits ?? []; const progress=Math.max(0,Math.min(100,props.readiness?.displayProgress ?? 0));
  const actions: [BriefWorkflowAction,string][]=[["revise","Revise content"],["evidence","Submit evidence"],["finding","Record finding"],["resolve_finding","Resolve finding"],["condition","Raise condition"],["resolve_condition","Resolve condition"],["propose_na","Propose N/A"],["review_na","Review N/A"],["approve_na","Approve N/A"],["review","Accept review"],["approve","Approve section"]];
  return <div className="space-y-4" dir={dir}>
    <div className="flex flex-col gap-3 rounded-xl border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="font-semibold">{t("brief.title","Governed design brief")}</h2><p className="text-sm text-muted-foreground">Readiness and permissions are evaluated by the server.</p></div><label className="text-sm">Brief stream <select className="h-9 rounded-md border bg-background px-3" value={String(props.selectedStreamId??"")} onChange={e=>props.onSelectStream(e.target.value)}>{props.streams.map(s=><option key={s.id} value={String(s.id)}>{s.name??`Brief ${s.id}`} · {label(s.purpose)}</option>)}</select></label></div>
    <div className="rounded-lg border border-amber-500/40 bg-amber-500/10 p-4" role="status"><p className="flex items-center gap-2 font-semibold"><LockKeyhole className="h-4 w-4"/>WORKING DRAFT — NOT ISSUED</p><p className="text-sm text-muted-foreground">This preview is live working content. It is not an immutable issue, export, report, or public share.</p></div>
    <div className="grid gap-4 lg:grid-cols-[1fr_18rem]"><Tabs defaultValue="sections"><TabsList><TabsTrigger value="sections">{t("brief.sections","Ten sections")}</TabsTrigger><TabsTrigger value="preview">{t("brief.preview","Working preview")}</TabsTrigger></TabsList>
      <TabsContent value="sections" className="space-y-3">{sections.map((s,i)=>{const id=String(s.sectionId??s.sectionKey??i); const maturity=s.achievedState??s.maturityState??s.maturity; return <Card key={id}><CardContent className="space-y-3 p-4"><div className="flex justify-between"><h3 className="font-medium">{s.title??label(s.sectionId??s.sectionKey)}</h3><Badge>{label(maturity)}</Badge></div><div className="flex gap-2">{s.isStale&&<Badge variant="outline">Stale</Badge>}{s.isBlocked&&<Badge variant="destructive">Blocked</Badge>}</div>{props.onSectionAction&&<><Button size="sm" variant="outline" aria-expanded={open===id} onClick={()=>setOpen(open===id?undefined:id)}>Workflow actions</Button>{open===id&&<div className="space-y-2"><Textarea aria-label="Action detail" value={detail} onChange={e=>setDetail(e.target.value)}/><div className="grid gap-2 sm:grid-cols-3"><Input aria-label="Target ID" placeholder="Target event/record ID" value={target} onChange={e=>setTarget(e.target.value)}/><Input aria-label="Dependency IDs" placeholder="Dependency IDs, comma separated" value={deps} onChange={e=>setDeps(e.target.value)}/><Input aria-label="Owner user ID" placeholder="Owner user ID" value={owner} onChange={e=>setOwner(e.target.value)}/></div><div className="flex flex-wrap gap-2">{actions.map(([a,l])=><Button key={a} size="sm" variant="secondary" onClick={()=>props.onSectionAction?.(a,id,detail,target||undefined,deps.split(",").map(x=>x.trim()).filter(Boolean),Number(owner)||undefined)}>{l}</Button>)}</div></div>}</>}</CardContent></Card>})}</TabsContent>
      <TabsContent value="preview"><Card><CardHeader><CardTitle>Version {props.version?.versionNumber??props.version?.version??"—"} · {label(props.version?.purpose)}</CardTitle></CardHeader><CardContent className="space-y-5">{(props.version?.sections??sections).map((s,i)=><section key={s.sectionId??i}><h3 className="font-semibold">{label(s.sectionId)}</h3><pre className="whitespace-pre-wrap text-sm text-muted-foreground">{s.content==null?"No content available from the canonical version API.":typeof s.content==="string"?s.content:JSON.stringify(s.content,null,2)}</pre></section>)}</CardContent></Card></TabsContent></Tabs>
      <aside className="space-y-4" aria-label="Brief readiness"><Card><CardHeader><CardTitle>Issue readiness</CardTitle></CardHeader><CardContent className="space-y-3"><Progress value={progress} aria-label={`Brief display progress ${progress}%`}/><p>{progress}%</p>{props.readiness?.canIssue&&<Badge><CheckCircle2 className="me-1 h-3 w-3"/>Ready</Badge>}<Button className="w-full" disabled={!props.canAttemptIssue||props.isIssuing} onClick={props.onIssue}>Issue immutable brief</Button></CardContent></Card><Card><CardHeader><CardTitle>Required next actions</CardTitle></CardHeader><CardContent><ul className="space-y-2">{reasons.map((r,i)=><li key={`${r.code}-${i}`} className="text-sm"><b>{r.message??label(r.code)}</b><p className="text-muted-foreground">{r.nextAction}</p></li>)}</ul></CardContent></Card>
      {props.onCreateVersion&&<Button variant="outline" className="w-full" onClick={props.onCreateVersion}>Create successor version</Button>}<Card><CardHeader><CardTitle>Issue ledger</CardTitle></CardHeader><CardContent>{props.issues?.length?<ul className="space-y-2 text-sm">{props.issues.map((issue:any)=><li key={issue.id}>Issue {issue.issueNumber??issue.id} · {label(issue.status??"active")}</li>)}</ul>:<p className="text-sm text-muted-foreground">No issued versions.</p>}</CardContent></Card>{(props.onAssignRole||props.onRevokeRole)&&<Card><CardHeader><CardTitle>Functional roles</CardTitle></CardHeader><CardContent className="space-y-2"><Input aria-label="User ID" value={roleUser} onChange={e=>setRoleUser(e.target.value)}/><select aria-label="Role" className="h-9 w-full border bg-background" value={role} onChange={e=>setRole(e.target.value)}>{["author","section_owner","reviewer","approver","issuer","viewer"].map(r=><option key={r}>{r}</option>)}</select><Button onClick={()=>props.onAssignRole?.(Number(roleUser),role)} disabled={!Number(roleUser)}>Assign</Button><Input aria-label="Grant event ID" value={grant} onChange={e=>setGrant(e.target.value)}/><Button variant="outline" onClick={()=>props.onRevokeRole?.(grant)} disabled={!grant}>Revoke</Button></CardContent></Card>}</aside></div>
  </div>;
}
