CREATE TABLE `trend_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metric` varchar(255) NOT NULL,
	`category` varchar(128) NOT NULL,
	`geography` varchar(128) NOT NULL,
	`dataPointCount` int NOT NULL DEFAULT 0,
	`gradeACount` int NOT NULL DEFAULT 0,
	`gradeBCount` int NOT NULL DEFAULT 0,
	`gradeCCount` int NOT NULL DEFAULT 0,
	`uniqueSources` int NOT NULL DEFAULT 0,
	`dateRangeStart` timestamp,
	`dateRangeEnd` timestamp,
	`currentMA` decimal(14,4),
	`previousMA` decimal(14,4),
	`percentChange` decimal(10,6),
	`direction` enum('rising','falling','stable','insufficient_data') NOT NULL,
	`anomalyCount` int NOT NULL DEFAULT 0,
	`anomalyDetails` json,
	`trendConfidence` enum('high','medium','low','insufficient') NOT NULL,
	`narrative` text,
	`movingAverages` json,
	`ingestionRunId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `trend_snapshots_id` PRIMARY KEY(`id`)
);
