CREATE TABLE `dld_area_benchmarks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`area_id` int NOT NULL,
	`area_name_en` varchar(200) NOT NULL,
	`property_type` varchar(100),
	`period` varchar(10) NOT NULL,
	`sale_p25` decimal(10,2),
	`sale_p50` decimal(10,2),
	`sale_p75` decimal(10,2),
	`sale_mean` decimal(10,2),
	`sale_transaction_count` int DEFAULT 0,
	`sale_yoy_change_pct` decimal(6,2),
	`rent_p50` decimal(10,2),
	`rent_mean` decimal(10,2),
	`rent_transaction_count` int DEFAULT 0,
	`gross_yield` decimal(6,2),
	`absorption_rate` decimal(6,4),
	`recommended_fitout_low` decimal(10,2),
	`recommended_fitout_mid` decimal(10,2),
	`recommended_fitout_high` decimal(10,2),
	`computed_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dld_area_benchmarks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dld_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`project_id` bigint NOT NULL,
	`project_number` int,
	`project_name` varchar(500),
	`project_description_en` text,
	`project_status` varchar(50),
	`project_classification` varchar(50),
	`project_type` varchar(50),
	`area_id` int,
	`area_name_en` varchar(200),
	`area_name_ar` varchar(200),
	`master_project_en` varchar(300),
	`master_project_ar` varchar(300),
	`developer_name` varchar(500),
	`developer_number` int,
	`master_developer_name` varchar(500),
	`zoning_authority_en` varchar(200),
	`escrow_agent_name` varchar(500),
	`no_of_units` int DEFAULT 0,
	`no_of_villas` int DEFAULT 0,
	`no_of_buildings` int DEFAULT 0,
	`no_of_lands` int DEFAULT 0,
	`percent_completed` int DEFAULT 0,
	`project_start_date` varchar(20),
	`project_end_date` varchar(20),
	`completion_date` varchar(20),
	`property_id` bigint,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dld_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dld_rents` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contract_id` varchar(50),
	`contract_reg_type_en` varchar(50),
	`ejari_property_type_en` varchar(100),
	`ejari_property_sub_type_en` varchar(100),
	`property_usage_en` varchar(100),
	`area_id` int,
	`area_name_en` varchar(200),
	`project_name_en` varchar(300),
	`master_project_en` varchar(300),
	`annual_amount` decimal(12,2),
	`contract_amount` decimal(12,2),
	`actual_area` decimal(10,2),
	`rent_per_sqm` decimal(10,2),
	`contract_start_date` varchar(20),
	`contract_end_date` varchar(20),
	`tenant_type_en` varchar(50),
	`is_free_hold` int,
	`nearest_metro_en` varchar(200),
	`nearest_mall_en` varchar(200),
	`nearest_landmark_en` varchar(200),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dld_rents_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `dld_transactions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transaction_id` varchar(50),
	`trans_group_en` varchar(50),
	`procedure_name_en` varchar(100),
	`reg_type_en` varchar(50),
	`property_type_en` varchar(50),
	`property_sub_type_en` varchar(100),
	`property_usage_en` varchar(50),
	`area_id` int,
	`area_name_en` varchar(200),
	`project_name_en` varchar(300),
	`building_name_en` varchar(300),
	`master_project_en` varchar(300),
	`actual_worth` decimal(14,2),
	`procedure_area` decimal(10,2),
	`meter_sale_price` decimal(10,2),
	`rooms_en` varchar(30),
	`instance_date` varchar(20),
	`has_parking` int,
	`nearest_metro_en` varchar(200),
	`nearest_mall_en` varchar(200),
	`nearest_landmark_en` varchar(200),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `dld_transactions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
ALTER TABLE `projects` ADD `dld_area_id` int;--> statement-breakpoint
ALTER TABLE `projects` ADD `dld_area_name` varchar(200);--> statement-breakpoint
ALTER TABLE `projects` ADD `city` enum('Dubai','Abu Dhabi') DEFAULT 'Dubai';--> statement-breakpoint
ALTER TABLE `projects` ADD `sustain_cert_target` varchar(50) DEFAULT 'silver';--> statement-breakpoint
ALTER TABLE `projects` ADD `project_purpose` enum('sell_offplan','sell_ready','rent','mixed') DEFAULT 'sell_ready';