import {
  reportDirection,
  reportLanguageTag,
  type ReportDirection,
  type ReportLocale,
} from "../../shared/report-locale";

/**
 * Versioned deterministic copy for issued reports. This catalog is deliberately
 * server-owned: browser UI dictionaries are not a source of record for report
 * labels, financial qualifiers, or disclaimers.
 *
 * Arabic legal/financial wording is a release gate. Catalog version v1 received
 * the product/report-owner approval recorded by TR-10 on 2026-07-18.
 */
export const REPORT_COPY_VERSION = "tr10-report-copy-v1";
export const REPORT_COPY_REVIEW_STATUS = "approved_2026_07_18" as const;

const EN_COPY = {
  language: "Report language",
  english: "English",
  arabic: "Arabic",
  generated: "Generated",
  generatedAt: "Generated at",
  documentId: "Document ID",
  renderInputFingerprint: "Render-input fingerprint",
  renderInputFingerprintHelp: "Debugging fingerprint of the documented render inputs; it is not an immutable issued snapshot or evidence-chain hash.",
  artifactVersion: "Artifact version",
  rendererVersion: "Renderer version",
  modelVersion: "Model version",
  benchmarkVersion: "Benchmark version",
  logicVersion: "Logic version",
  reportLocale: "Report language",
  readOnly: "Read-only",
  sharedBrief: "Shared brief",
  expires: "Expires",
  linkUnavailable: "Link unavailable",
  sharedLinkUnavailable: "This share link is invalid or has expired.",
  loadingSharedBrief: "Loading shared brief…",
  noData: "No data available.",
  noContentGenerated: "No content generated.",
  noAllocations: "No allocations available.",
  notAvailable: "—",
  confidentialInternalOnly: "Confidential — For Internal Use Only",
  executiveDecisionPack: "Executive Decision Pack",
  validationSummarySubtitle: "Interior Design Direction Assessment",
  designBriefTitle: "Interior Design Instruction Brief",
  designBriefSubtitle: "Technical Specification & Execution Workflows",
  fullReport: "Full Evaluation Report",
  fullReportSubtitle: "Comprehensive Decision Intelligence Analysis",
  autonomousDesignBrief: "Autonomous Design Brief",
  autonomousDesignBriefSubtitle: "AI-Generated Concept & Technical Specification",
  scenarioComparisonPack: "Scenario Comparison Pack",
  scenarioComparisonSubtitle: "Decision Trade-off Analysis",
  scenarioPoints: "points",
  portfolioReport: "Portfolio Intelligence Report",
  portfolioTotalProjects: "Total Projects",
  portfolioScored: "Scored",
  portfolioAverageComposite: "Avg Composite",
  portfolioAverageRisk: "Avg Risk",
  portfolioGeneratedBy: "Generated by MIYAR Decision Intelligence",
  portfolioId: "Portfolio ID",
  portfolioProjectsAnalyzed: "projects analyzed",
  portfolioConditional: "Conditional",
  materialBoard: "Material Board",
  investorSummary: "Investor Summary",
  executiveSummary: "Executive Summary",
  dimensionScores: "Dimension Scores",
  radarProfile: "Radar Profile",
  riskAssessment: "Risk Assessment",
  sensitivityAnalysis: "Sensitivity Analysis",
  conditionalActions: "Conditional Actions",
  designDirectionParameters: "Design Direction Parameters",
  variableContributions: "Variable Contributions",
  roiAnalysis: "ROI Analysis",
  evidenceReferences: "Evidence References",
  evidenceReferenceDescription: "The following evidence records were linked to this project at the time of report generation.",
  evidenceInlineCitationHelp: "Inline citations [n] in the report body reference entries in this table.",
  evidenceGradeLegend: "Grade A = Primary institutional source | Grade B = Verified commercial source | Grade C = Self-reported or unverified",
  confidenceProvenance: "Confidence provenance",
  legacyCalculationProvenanceUnavailable: "Legacy — calculation provenance unavailable",
  operatorAssertedConfidence: "Operator asserted ({policy})",
  computedConfidence: "Computed ({policy})",
  evidenceLink: "[link]",
  evidenceTrace: "Evidence Trace & Render Context",
  inputSummary: "Input Summary",
  materialBoardAnnex: "Material Board Annex",
  scenarioScoreComparison: "Scenario Score Comparison",
  roiComparison: "ROI Comparison",
  tradeoffAnalysis: "Trade-off Analysis",
  decisionNote: "Decision Note",
  baseline: "Baseline",
  scenario: "Scenario",
  dimension: "Dimension",
  compositeScore: "Composite Score",
  roiMetric: "ROI Metric",
  amountAed: "Amount (AED)",
  roiNarrativeFallbackDenominator: "ROI multiple is calculated as total value divided by the ungoverned MIYAR fallback denominator of AED 150,000. It is indicative only and is not a market valuation or investment recommendation.",
  totalValueCreated: "Total Value Created",
  reworkAvoided: "Rework Avoided",
  procurementSavings: "Procurement Savings",
  timeValueGain: "Time-Value Gain",
  projectIdentity: "Project Identity",
  designNarrative: "Design Narrative",
  materialSpecifications: "Material Specifications",
  targetBoqFramework: "Target BOQ Framework",
  detailedBudgetGuardrails: "Detailed Budget Guardrails",
  workflowExecutionInstructions: "Workflow and Execution Instructions",
  phasedDeliverables: "Phased Deliverables",
  parameter: "Parameter",
  title: "Title",
  value: "Value",
  category: "Category",
  allocation: "Allocation",
  estimatedBudget: "Estimated Budget",
  notes: "Notes",
  source: "Source",
  captured: "Captured",
  grade: "Grade",
  reference: "Reference",
  validated: "Validated",
  conditionallyValidated: "Conditionally validated",
  notValidated: "Not validated",
  recommendedActions: "Recommended Actions",
  noConditionalActions: "No conditional actions required. All parameters are within acceptable ranges.",
  conditionalActionsIdentified: "{count} conditional action(s) identified:",
  actionTrigger: "Trigger:",
  actionRecommendation: "Recommendation:",
  actionVariables: "Variables:",
  importantDisclaimer: "Important disclaimer",
  disclaimer: "This document is a concept-level assessment generated by the MIYAR Decision Intelligence Platform. Scores, recommendations, specifications, cost estimates, and procurement guidance are advisory only. They require detailed design, engineering review, professional validation, and formal tender confirmation where applicable. MIYAR does not warrant third-party benchmark data or market intelligence. This document is not professional design, financial, or legal advice.",
  investorFallbackAssumption: "Ungoverned MIYAR fallback assumption",
  investorFallbackAssumptionHelp: "This calculation uses hardcoded MIYAR tier mappings and the AED 25,000 per m² baseline unconditionally, regardless of available project evidence. It is indicative only and must not be treated as a market valuation or investment recommendation.",
  scoresAdvisory: "Scores are advisory and do not constitute professional design or financial advice.",
  allSpaces: "All spaces",
  costPerSquareMetre: "Cost / m²",
  totalFitout: "Total fit-out",
  designPremium: "Design premium",
  sensitivityIntroduction: "Top {count} variables ranked by impact on composite score when adjusted ±1 unit:",
  boardEmptyResolution: "Empty board — no materials are attached. Cost and lead-time summary is unavailable.",
  boardUnresolvableResolution: "Unresolvable board — none of the {linked} linked items could be resolved. Cost and lead-time summary is unavailable; repair the board links before relying on it.",
  boardPartialResolution: "Partial board — {resolved} of {linked} linked items resolved. {unresolved} unresolved {itemStatus} excluded from the figures below.",
  boardCompleteSingleResolution: "Complete board — the linked item is resolved.",
  boardCompleteMultipleResolution: "Complete board — all {linked} linked items are resolved.",
  boardResolvedCount: "{resolved} of {linked} items resolved",
  boardItemIs: "item is",
  boardItemsAre: "items are",
  resolvedItemCostRange: "Resolved-item Cost Range",
  resolvedItemLongestLead: "Resolved-item Longest Lead",
  resolvedCriticalItems: "Resolved Critical Items",
  materialBoardAnnexDescription: "Board availability and resolution are shown explicitly. Any figures shown are calculated only from resolved catalog items. Full RFQ-ready procurement schedules are available via the Board Composer export.",
  noMaterialBoards: "No material boards have been created for this project. Use the Board Composer to build material boards with cost estimates and RFQ-ready procurement schedules.",
} as const;

export type ReportCopyKey = keyof typeof EN_COPY;

const AR_COPY: Record<ReportCopyKey, string> = {
  language: "لغة التقرير",
  english: "الإنجليزية",
  arabic: "العربية",
  generated: "تم الإنشاء",
  generatedAt: "تاريخ الإنشاء",
  documentId: "معرّف المستند",
  renderInputFingerprint: "بصمة مدخلات العرض",
  renderInputFingerprintHelp: "بصمة تصحيح أخطاء لمدخلات العرض الموثقة؛ وليست لقطة إصدار غير قابلة للتغيير أو تجزئة لسلسلة أدلة.",
  artifactVersion: "إصدار المخرج",
  rendererVersion: "إصدار محرك العرض",
  modelVersion: "إصدار النموذج",
  benchmarkVersion: "إصدار المعيار المرجعي",
  logicVersion: "إصدار المنطق",
  reportLocale: "لغة التقرير",
  readOnly: "للعرض فقط",
  sharedBrief: "موجز مشترك",
  expires: "تنتهي الصلاحية",
  linkUnavailable: "الرابط غير متاح",
  sharedLinkUnavailable: "رابط المشاركة هذا غير صالح أو انتهت صلاحيته.",
  loadingSharedBrief: "جارٍ تحميل الموجز المشترك…",
  noData: "لا توجد بيانات متاحة.",
  noContentGenerated: "لم يتم إنشاء محتوى.",
  noAllocations: "لا توجد تخصيصات متاحة.",
  notAvailable: "—",
  confidentialInternalOnly: "سري — للاستخدام الداخلي فقط",
  executiveDecisionPack: "حزمة القرار التنفيذي",
  validationSummarySubtitle: "تقييم توجه التصميم الداخلي",
  designBriefTitle: "موجز تعليمات التصميم الداخلي",
  designBriefSubtitle: "المواصفات الفنية وإجراءات التنفيذ",
  fullReport: "تقرير التقييم الكامل",
  fullReportSubtitle: "تحليل شامل لذكاء القرار",
  autonomousDesignBrief: "موجز التصميم المستقل",
  autonomousDesignBriefSubtitle: "مواصفات مفاهيمية وفنية مولّدة بالذكاء الاصطناعي",
  scenarioComparisonPack: "حزمة مقارنة السيناريوهات",
  scenarioComparisonSubtitle: "تحليل المفاضلات في القرار",
  scenarioPoints: "نقطة",
  portfolioReport: "تقرير ذكاء المحفظة",
  portfolioTotalProjects: "إجمالي المشاريع",
  portfolioScored: "المشاريع المقيّمة",
  portfolioAverageComposite: "متوسط الدرجة المركبة",
  portfolioAverageRisk: "متوسط المخاطر",
  portfolioGeneratedBy: "أُنشئ بواسطة MIYAR لذكاء القرار",
  portfolioId: "معرّف المحفظة",
  portfolioProjectsAnalyzed: "مشروعاً تم تحليله",
  portfolioConditional: "مشروط",
  materialBoard: "لوحة المواد",
  investorSummary: "ملخص المستثمر",
  executiveSummary: "الملخص التنفيذي",
  dimensionScores: "درجات الأبعاد",
  radarProfile: "ملف الرادار",
  riskAssessment: "تقييم المخاطر",
  sensitivityAnalysis: "تحليل الحساسية",
  conditionalActions: "الإجراءات المشروطة",
  designDirectionParameters: "معايير توجه التصميم",
  variableContributions: "مساهمات المتغيرات",
  roiAnalysis: "تحليل العائد على الاستثمار",
  evidenceReferences: "مراجع الأدلة",
  evidenceReferenceDescription: "تم ربط سجلات الأدلة التالية بهذا المشروع عند إنشاء التقرير.",
  evidenceInlineCitationHelp: "تشير الاستشهادات المضمنة [n] في متن التقرير إلى الإدخالات الواردة في هذا الجدول.",
  evidenceGradeLegend: "الدرجة A = مصدر مؤسسي أولي | الدرجة B = مصدر تجاري تم التحقق منه | الدرجة C = مُبلّغ عنه ذاتياً أو غير متحقق منه",
  confidenceProvenance: "مصدر الثقة",
  legacyCalculationProvenanceUnavailable: "قديم — مصدر الحساب غير متاح",
  operatorAssertedConfidence: "أكده المشغّل ({policy})",
  computedConfidence: "محسوب ({policy})",
  evidenceLink: "[رابط]",
  evidenceTrace: "سياق الأدلة والعرض",
  inputSummary: "ملخص المدخلات",
  materialBoardAnnex: "ملحق لوحة المواد",
  scenarioScoreComparison: "مقارنة درجات السيناريوهات",
  roiComparison: "مقارنة العائد على الاستثمار",
  tradeoffAnalysis: "تحليل المفاضلات",
  decisionNote: "ملاحظة القرار",
  baseline: "خط الأساس",
  scenario: "السيناريو",
  dimension: "البعد",
  compositeScore: "الدرجة المركبة",
  roiMetric: "مؤشر العائد على الاستثمار",
  amountAed: "المبلغ (درهم)",
  roiNarrativeFallbackDenominator: "يُحسب مضاعف العائد على الاستثمار بقسمة إجمالي القيمة على مقام احتياطي غير محكوم من MIYAR قدره 150,000 درهم. وهو استرشادي فقط ولا يمثل تقييماً سوقياً أو توصية استثمارية.",
  totalValueCreated: "إجمالي القيمة المتحققة",
  reworkAvoided: "إعادة العمل المتجنبة",
  procurementSavings: "وفورات الشراء",
  timeValueGain: "مكسب قيمة الوقت",
  projectIdentity: "هوية المشروع",
  designNarrative: "السرد التصميمي",
  materialSpecifications: "مواصفات المواد",
  targetBoqFramework: "إطار جدول الكميات المستهدف",
  detailedBudgetGuardrails: "ضوابط الميزانية التفصيلية",
  workflowExecutionInstructions: "تعليمات سير العمل والتنفيذ",
  phasedDeliverables: "المخرجات المرحلية",
  parameter: "المعيار",
  title: "العنوان",
  value: "القيمة",
  category: "الفئة",
  allocation: "التخصيص",
  estimatedBudget: "الميزانية التقديرية",
  notes: "ملاحظات",
  source: "المصدر",
  captured: "تاريخ الالتقاط",
  grade: "الدرجة",
  reference: "المرجع",
  validated: "تم التحقق",
  conditionallyValidated: "تم التحقق بشروط",
  notValidated: "لم يتم التحقق",
  recommendedActions: "الإجراءات الموصى بها",
  noConditionalActions: "لا توجد إجراءات مشروطة مطلوبة. جميع المعايير ضمن النطاقات المقبولة.",
  conditionalActionsIdentified: "تم تحديد {count} إجراء/إجراءات مشروطة:",
  actionTrigger: "المحفز:",
  actionRecommendation: "التوصية:",
  actionVariables: "المتغيرات:",
  importantDisclaimer: "إخلاء مسؤولية مهم",
  disclaimer: "هذا المستند تقييم على مستوى المفهوم أُنشئ بواسطة منصة MIYAR لذكاء القرار. الدرجات والتوصيات والمواصفات وتقديرات التكلفة وإرشادات الشراء استشارية فقط. وهي تتطلب تصميماً تفصيلياً ومراجعة هندسية وتحققاً مهنياً وتأكيداً من خلال مناقصة رسمية عند الاقتضاء. لا تضمن MIYAR بيانات المعايير المرجعية أو معلومات السوق المقدمة من أطراف ثالثة. هذا المستند ليس مشورة مهنية في التصميم أو الشؤون المالية أو القانونية.",
  investorFallbackAssumption: "افتراض احتياطي غير محكوم من MIYAR",
  investorFallbackAssumptionHelp: "يستخدم هذا الحساب تعيينات شرائح MIYAR مُشفّرة مسبقاً وأساساً قدره 25,000 درهم لكل م² دون قيد، بصرف النظر عن توفر أدلة المشروع. وهو استرشادي فقط ولا يجوز اعتباره تقييماً سوقياً أو توصية استثمارية.",
  scoresAdvisory: "الدرجات استشارية ولا تشكل مشورة مهنية في التصميم أو الشؤون المالية.",
  allSpaces: "جميع المساحات",
  costPerSquareMetre: "التكلفة / م²",
  totalFitout: "إجمالي التجهيز الداخلي",
  designPremium: "العلاوة التصميمية",
  sensitivityIntroduction: "أعلى {count} متغيرات مرتبة بحسب أثرها في الدرجة المركبة عند تعديلها بمقدار ±1 وحدة:",
  boardEmptyResolution: "لوحة فارغة — لا توجد مواد مرفقة. ملخص التكلفة والمهلة غير متاح.",
  boardUnresolvableResolution: "لوحة غير قابلة للحل — لم يتم حل أي من العناصر المرتبطة وعددها {linked}. ملخص التكلفة والمهلة غير متاح؛ أصلح روابط اللوحة قبل الاعتماد عليها.",
  boardPartialResolution: "لوحة جزئية — تم حل {resolved} من أصل {linked} عناصر مرتبطة. استُبعد {unresolved} {itemStatus} غير محلول من الأرقام أدناه.",
  boardCompleteSingleResolution: "لوحة مكتملة — تم حل العنصر المرتبط.",
  boardCompleteMultipleResolution: "لوحة مكتملة — تم حل جميع العناصر المرتبطة وعددها {linked}.",
  boardResolvedCount: "تم حل {resolved} من أصل {linked} عناصر",
  boardItemIs: "عنصر",
  boardItemsAre: "عناصر",
  resolvedItemCostRange: "نطاق تكلفة العناصر المحلولة",
  resolvedItemLongestLead: "أطول مهلة للعناصر المحلولة",
  resolvedCriticalItems: "العناصر الحرجة المحلولة",
  materialBoardAnnexDescription: "يتم عرض توفر اللوحات وحالة حل عناصرها بوضوح. تُحسب الأرقام المعروضة فقط من عناصر الكتالوج التي تم حلها. تتوفر جداول شراء كاملة جاهزة لطلب عروض الأسعار عبر تصدير أداة إنشاء اللوحات.",
  noMaterialBoards: "لم يتم إنشاء لوحات مواد لهذا المشروع. استخدم أداة إنشاء اللوحات لبناء لوحات مواد تتضمن تقديرات التكلفة وجداول شراء جاهزة لطلب عروض الأسعار.",
};

/** Fixed copy still emitted by the legacy project/scenario/portfolio templates. */
const LEGACY_REPORT_AR_COPY: Readonly<Record<string, string>> = {
  "Decision Tradeoff Analysis": "تحليل المفاضلات في القرار",
  "Portfolio Analysis Report": "تقرير تحليل المحفظة",
  "Multi-Project Decision Intelligence Summary": "ملخص ذكاء القرار متعدد المشاريع",
  "Portfolio Executive Summary": "الملخص التنفيذي للمحفظة",
  "Project Comparison": "مقارنة المشاريع",
  "Score Distributions by Dimension": "توزيعات الدرجات حسب البعد",
  "Failure Patterns": "أنماط الإخفاق",
  "Improvement Levers": "عوامل التحسين",
  "Compliance Heatmap (Tier × Dimension)": "الخريطة الحرارية للامتثال (الشريحة × البعد)",
  "Strategic Alignment": "المواءمة الاستراتيجية",
  "Financial Feasibility": "الجدوى المالية",
  "Market Positioning": "التموضع السوقي",
  "Differentiation Strength": "قوة التمايز",
  "Execution Risk": "مخاطر التنفيذ",
  "Evidence Trace & Provenance": "تتبع الأدلة ومصدرها",
  "Risk Score": "درجة المخاطر",
  "Penalties Applied": "العقوبات المطبقة",
  "Active Penalties": "العقوبات النشطة",
  "Risk Flags": "تنبيهات المخاطر",
  "No risk flags triggered.": "لم يتم تفعيل أي تنبيهات مخاطر.",
  "Recommended Actions": "الإجراءات الموصى بها",
  "No conditional actions required. All parameters are within acceptable ranges.": "لا توجد إجراءات مشروطة مطلوبة. جميع المعايير ضمن النطاقات المقبولة.",
  "Project Input Summary": "ملخص مدخلات المشروع",
  "Variable Contribution Analysis": "تحليل مساهمة المتغيرات",
  "ROI & Economic Impact Analysis": "تحليل العائد على الاستثمار والأثر الاقتصادي",
  "Value Breakdown": "تفصيل القيمة",
  "Executive Narrative": "السرد التنفيذي",
  "Key Assumptions": "الافتراضات الرئيسية",
  "5-Lens Defensibility Framework": "إطار القابلية للدفاع بخمس عدسات",
  "Overall Defensibility": "القابلية للدفاع إجمالاً",
  "Weakest Lens": "أضعف عدسة",
  "Table of Contents": "جدول المحتويات",
  "Design Narrative & Positioning": "السرد التصميمي والتموضع",
  "Design Narrative &amp; Positioning": "السرد التصميمي والتموضع",
  "Primary Style": "الأسلوب الأساسي",
  "Mood Keywords": "كلمات الأجواء",
  "Color Palette": "لوحة الألوان",
  "Texture Direction": "توجه الملمس",
  "Lighting Approach": "نهج الإضاءة",
  "Tier Requirement": "متطلب الشريحة",
  "Quality Benchmark": "معيار الجودة",
  "Sustainability": "الاستدامة",
  "Approved Materials (Primary)": "المواد المعتمدة (الأساسية)",
  "Approved Finishes & Textures": "التشطيبات والملامس المعتمدة",
  "Approved Finishes &amp; Textures": "التشطيبات والملامس المعتمدة",
  "Prohibited Materials (Value Engineering Flags)": "المواد المحظورة (تنبيهات هندسة القيمة)",
  "Total Estimated Project Area": "إجمالي مساحة المشروع التقديرية",
  "Cost Per Sqm Target": "التكلفة المستهدفة لكل م²",
  "Total Budget Cap": "الحد الأعلى للميزانية",
  "Cost Band": "نطاق التكلفة",
  "Contingency": "الاحتياطي",
  "Flexibility Level": "مستوى المرونة",
  "Value Engineering Directives": "توجيهات هندسة القيمة",
  "Lead Time Window": "نافذة المهلة الزمنية",
  "Critical Path Procurement Items": "عناصر الشراء على المسار الحرج",
  "Local Authority Approvals (Dubai)": "اعتمادات الجهات المحلية (دبي)",
  "Contractor Coordination Requirements": "متطلبات التنسيق مع المقاول",
  "Phase 1 — Concept & Schematic": "المرحلة 1 — المفهوم والتصميم التخطيطي",
  "Phase 2 — Detailed Design": "المرحلة 2 — التصميم التفصيلي",
  "Phase 3 — IFC & Tender": "المرحلة 3 — مخططات التنفيذ والمناقصة",
  "Phase 1 — Concept &amp; Schematic": "المرحلة 1 — المفهوم والتصميم التخطيطي",
  "Phase 3 — IFC &amp; Tender": "المرحلة 3 — مخططات التنفيذ والمناقصة",
  "Technical Specification &amp; Execution Workflows": "المواصفات الفنية وإجراءات التنفيذ",
  "AI-Generated Concept &amp; Technical Specification": "مواصفات مفاهيمية وفنية مولّدة بالذكاء الاصطناعي",
  "Workflow &amp; Execution Instructions": "تعليمات سير العمل والتنفيذ",
  "No material boards have been created for this project. Use the Board Composer to build material boards with cost estimates and RFQ-ready procurement schedules.": "لم يتم إنشاء لوحات مواد لهذا المشروع. استخدم أداة إنشاء اللوحات لبناء لوحات مواد تتضمن تقديرات التكلفة وجداول شراء جاهزة لطلب عروض الأسعار.",
  "Board availability and resolution are shown explicitly. Any figures shown are calculated only from resolved catalog items. Full RFQ-ready procurement schedules are available via the Board Composer export.": "يتم عرض توفر اللوحات وحالة حل عناصرها بوضوح. تُحسب الأرقام المعروضة فقط من عناصر الكتالوج التي تم حلها. تتوفر جداول شراء كاملة جاهزة لطلب عروض الأسعار عبر تصدير أداة إنشاء اللوحات.",
  "Scenario": "السيناريو", "Baseline": "خط الأساس", "Variable": "المتغير",
  "Sensitivity": "الحساسية", "Range": "النطاق", "Weight": "الوزن",
  "Weighted Score": "الدرجة الموزونة", "Status": "الحالة", "Decision": "القرار",
  "Project": "المشروع", "Tier": "الشريحة", "Style": "الأسلوب", "Risk": "المخاطر",
  "Group": "المجموعة", "Count": "العدد", "Avg Score": "متوسط الدرجة",
  "Description": "الوصف", "Impact": "الأثر", "Contribution": "المساهمة",
  "Trigger": "المحفز", "Recommendation": "التوصية", "Variables": "المتغيرات",
  "Improvements vs Baseline": "التحسينات مقابل خط الأساس",
  "Trade-offs vs Baseline": "المفاضلات مقابل خط الأساس",
  "No improvements over baseline.": "لا توجد تحسينات مقارنة بخط الأساس.",
  "No trade-offs identified.": "لم يتم تحديد مفاضلات.",
  "Confidence provenance": "مصدر الثقة",
  "Legacy — calculation provenance unavailable": "قديم — مصدر الحساب غير متاح",
  "VALIDATED": "تم التحقق",
  "CONDITIONALLY VALIDATED": "تم التحقق بشروط",
  "NOT VALIDATED": "لم يتم التحقق",
  Excellent: "ممتاز", Strong: "قوي", Moderate: "متوسط", Weak: "ضعيف", Critical: "حرج",
  High: "مرتفع", Low: "منخفض",
  Confidence: "الثقة", "Risk-Adjusted Score": "الدرجة المعدلة حسب المخاطر",
  "Dimension Score Breakdown": "تفصيل درجات الأبعاد",
  "Score (0-100)": "الدرجة (0-100)", Weighted: "الدرجة الموزونة", Composite: "الدرجة المركبة",
  "Sensitivity Analysis": "تحليل الحساسية", "Top": "أعلى",
  "Score (+1)": "الدرجة (+1)", "Score (-1)": "الدرجة (-1)",
  Context: "السياق", Strategy: "الاستراتيجية", Market: "السوق", Financial: "المالي", Design: "التصميم", Execution: "التنفيذ",
  Typology: "نوع المشروع", Scale: "الحجم", "Gross Floor Area (sqm)": "المساحة الإجمالية (م²)",
  "Interior Fit-out Area (sqm)": "مساحة التجهيز الداخلي (م²)", "Fitout Efficiency Ratio": "نسبة كفاءة التجهيز الداخلي",
  Location: "الموقع", "Delivery Horizon": "أفق التسليم", City: "المدينة", "Brand Clarity": "وضوح العلامة التجارية",
  Differentiation: "التميّز", "Buyer Maturity": "نضج المشتري", "Market Tier": "شريحة السوق",
  "Competitor Intensity": "حدة المنافسة", "Trend Sensitivity": "حساسية الاتجاهات", "Budget Cap (AED/sqm)": "الحد الأعلى للميزانية (درهم/م²)",
  Flexibility: "المرونة", "Shock Tolerance": "تحمل الصدمات", "Sales Premium": "علاوة المبيعات",
  "Material Level": "مستوى المواد", Complexity: "التعقيد", Experience: "التجربة",
  "Supply Chain": "سلسلة التوريد", Contractor: "المقاول", Approvals: "الاعتمادات", "QA Maturity": "نضج ضمان الجودة",
  "How each input variable contributes to each dimension score:": "كيف يساهم كل متغير إدخال في درجة كل بُعد:",
  "ROI Multiple": "مضاعف العائد على الاستثمار", "Value Component": "مكوّن القيمة", Conservative: "متحفظ", Base: "أساسي", Aggressive: "متفائل",
  "Spec Efficiency": "كفاءة المواصفات", "Positioning Premium": "علاوة التموضع", "MIYAR Fee": "رسوم MIYAR", "Net ROI": "صافي العائد على الاستثمار",
  Evidence: "الأدلة", Gaps: "الفجوات", "Priority improvement area": "مجال التحسين ذي الأولوية",
  "Resolved-item Cost Range": "نطاق تكلفة العناصر المحلولة", "Resolved-item Longest Lead": "أطول مهلة للعناصر المحلولة",
  "Resolved Critical Items": "العناصر الحرجة المحلولة", "Empty board": "لوحة فارغة", "Partial board": "لوحة جزئية",
  "Complete board": "لوحة مكتملة", "Unresolvable board": "لوحة غير قابلة للحل", "Critical:": "حرج:",
  "items resolved": "عناصر تم حلها",
};

export const REPORT_COPY: Readonly<Record<ReportLocale, Readonly<Record<ReportCopyKey, string>>>> = {
  en: EN_COPY,
  ar: AR_COPY,
};

export function reportCopy(locale: ReportLocale, key: ReportCopyKey): string {
  return REPORT_COPY[locale][key];
}

const REPORT_INTL_LOCALES: Record<ReportLocale, string> = {
  en: "en-AE",
  ar: "ar-AE",
};

export function reportIntlLocale(locale: ReportLocale): string {
  return REPORT_INTL_LOCALES[locale];
}

export function formatReportNumber(
  value: number,
  locale: ReportLocale,
  options: Intl.NumberFormatOptions = {},
): string {
  if (!Number.isFinite(value)) return reportCopy(locale, "notAvailable");
  return new Intl.NumberFormat(reportIntlLocale(locale), options).format(value);
}

export function formatReportAed(
  value: number,
  locale: ReportLocale,
  options: Omit<Intl.NumberFormatOptions, "style" | "currency"> = {},
): string {
  if (!Number.isFinite(value)) return reportCopy(locale, "notAvailable");
  return new Intl.NumberFormat(reportIntlLocale(locale), {
    style: "currency",
    currency: "AED",
    maximumFractionDigits: 0,
    ...options,
  }).format(value);
}

function toValidDate(value: Date | string | number): Date | null {
  const date = value instanceof Date ? value : new Date(value);
  return Number.isNaN(date.getTime()) ? null : date;
}

export function formatReportDate(
  value: Date | string | number,
  locale: ReportLocale,
  options: Intl.DateTimeFormatOptions = { year: "numeric", month: "long", day: "numeric" },
): string {
  const date = toValidDate(value);
  if (!date) return reportCopy(locale, "notAvailable");
  return new Intl.DateTimeFormat(reportIntlLocale(locale), options).format(date);
}

export function formatReportDateTime(value: Date | string | number, locale: ReportLocale): string {
  return formatReportDate(value, locale, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
}

export interface ReportDocumentMetadata {
  lang: "en" | "ar";
  dir: ReportDirection;
  fontFamily: string;
  dynamicTextDir: "auto";
}

/**
 * Renderer-ready metadata. Dynamic user/evidence values still need normal HTML
 * escaping at their interpolation boundary; this helper only supplies bidi
 * metadata and never marks arbitrary content safe.
 */
export function reportDocumentMetadata(locale: ReportLocale): ReportDocumentMetadata {
  return {
    lang: reportLanguageTag(locale),
    dir: reportDirection(locale),
    fontFamily: locale === "ar"
      ? '"Noto Sans Arabic", "Segoe UI", Tahoma, Arial, sans-serif'
      : '"Manrope", "Segoe UI", Tahoma, Arial, sans-serif',
    dynamicTextDir: "auto",
  };
}

/** CSS declarations common to standalone HTML artifacts. */
export function reportLocaleCss(locale: ReportLocale): string {
  const metadata = reportDocumentMetadata(locale);
  return [
    `html { direction: ${metadata.dir}; }`,
    `body { font-family: ${metadata.fontFamily}; direction: ${metadata.dir}; }`,
    "[data-report-dynamic] { unicode-bidi: plaintext; }",
    "table { direction: inherit; }",
    "th, td { text-align: start; }",
  ].join("\n");
}

/**
 * Deterministically replace governed fixed English report copy after a legacy
 * template has assembled its HTML. Dynamic project/evidence text is escaped at
 * its interpolation boundary and is intentionally never translated here.
 */
export function localizeGovernedReportCopy(html: string, locale: ReportLocale): string {
  if (locale === "en") return html;
  const governed = (Object.keys(EN_COPY) as ReportCopyKey[])
    .map(key => [EN_COPY[key], AR_COPY[key]] as const)
  const replacements = [...governed, ...Object.entries(LEGACY_REPORT_AR_COPY)]
    .sort((a, b) => b[0].length - a[0].length);
  const localizeStaticSegment = (segment: string) =>
    replacements.reduce((output, [english, arabic]) => output.replaceAll(english, arabic), segment);

  // Dynamic project, evidence, material, and LLM narrative values are emitted
  // in these wrappers. Localize only the surrounding governed template copy.
  const dynamicValue = /<(?:bdi|span)\b[^>]*\bdata-report-dynamic\b[^>]*>[\s\S]*?<\/(?:bdi|span)>/g;
  let output = "";
  let index = 0;
  for (const match of Array.from(html.matchAll(dynamicValue))) {
    const start = match.index ?? 0;
    output += localizeStaticSegment(html.slice(index, start));
    output += match[0];
    index = start + match[0].length;
  }
  return output + localizeStaticSegment(html.slice(index));
}
