import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

const mocks = vi.hoisted(() => ({ storagePut: vi.fn() }));
vi.mock("server/storage", () => ({ storagePut: mocks.storagePut }));

import { generateImage } from "./imageGeneration";

const VALID_PNG_BASE64 = "iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAIAAAD91JpzAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAAEklEQVQImWMwTptpnDaTAUIBAB/uBMm6iK1UAAAAAElFTkSuQmCC";
const originalKey = process.env.GEMINI_API_KEY;

function imageResponse(data = VALID_PNG_BASE64) {
  return new Response(JSON.stringify({ candidates: [{ content: { parts: [{ inlineData: { data, mimeType: "image/png" } }] } }] }), { status: 200 });
}

describe("generated-image media boundary", () => {
  beforeEach(() => {
    process.env.GEMINI_API_KEY = "test-key";
    mocks.storagePut.mockResolvedValue({ key: "generated/safe.png", url: "https://example.invalid/safe.png" });
    vi.stubGlobal("fetch", vi.fn());
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    vi.useRealTimers();
    vi.clearAllMocks();
    if (originalKey === undefined) delete process.env.GEMINI_API_KEY;
    else process.env.GEMINI_API_KEY = originalKey;
  });

  it("validates generated image bytes and persists canonical metadata", async () => {
    vi.mocked(fetch).mockResolvedValueOnce(imageResponse());

    await expect(generateImage({ prompt: "a valid image" })).resolves.toEqual(expect.objectContaining({
      url: "https://example.invalid/safe.png",
      mimeType: "image/png",
      storageKey: "generated/safe.png",
      checksum: expect.stringMatching(/^[a-f0-9]{64}$/),
    }));
    expect(mocks.storagePut).toHaveBeenCalledWith(
      expect.stringMatching(/^generated\/.*\.png$/),
      expect.any(Buffer),
      "image/png",
    );
  });

  it("maps provider rejection and malformed generated bytes to stable codes", async () => {
    vi.mocked(fetch).mockResolvedValueOnce(new Response('{"error":"provider-secret"}', { status: 400 }));
    await expect(generateImage({ prompt: "bad" })).rejects.toMatchObject({
      code: "PROVIDER_REJECTED_INPUT",
      message: expect.not.stringContaining("provider-secret"),
    });

    vi.mocked(fetch).mockResolvedValueOnce(imageResponse("not-an-image"));
    await expect(generateImage({ prompt: "bad bytes" })).rejects.toMatchObject({ code: "MEDIA_INVALID" });
    expect(mocks.storagePut).not.toHaveBeenCalled();
  });

  it("retries temporary provider failures at most twice", async () => {
    vi.useFakeTimers();
    const fetchMock = vi.mocked(fetch)
      .mockResolvedValueOnce(new Response("busy", { status: 429 }))
      .mockResolvedValueOnce(new Response("busy", { status: 503 }))
      .mockResolvedValueOnce(imageResponse());
    const generation = generateImage({ prompt: "retry" });
    await vi.runAllTimersAsync();

    await expect(generation).resolves.toMatchObject({ storageKey: "generated/safe.png" });
    expect(fetchMock).toHaveBeenCalledTimes(3);
  });
});
